<p>事务场景中，抛出异常被catch后，如果需要回滚，一定要手动回滚事务。</p>
<p>错例：</p>
<pre>
    @Transactional()
    public class TransactionOfClassMustHaveRollbackForExample {
        public int check() {
            Integer num = null;
        }
    }

</pre>
<pre>
public class TransactionOfMethodMustHaveRollbackOrRollbackForExample {
    @Transactional()
    public int check() {
        Integer num = null;
    }
}
</pre>
<p>正例：</p>
<pre>
    /**
     * @author caikang
     * @date 2017/04/07
     */
    @Service
    @Transactional(rollbackFor = Exception.class)
    public class UserServiceImpl implements UserService {
        @Override
        public void save(User user) {
            //some code
            //db operation
        }
    }
</pre>
<pre>
    /**
     * @author caikang
     * @date 2017/04/07
     */
    @Service
    public class UserServiceImpl implements UserService {
        @Override
        @Transactional(rollbackFor = Exception.class)
        public void save(User user) {
            //some code
            //db operation
        }
    }
</pre>
<pre>
    /**
     * @author caikang
     * @date 2017/04/07
     */
    @Service
    public class UserServiceImpl implements UserService {
        @Autowired
        private DataSourceTransactionManager transactionManager;

        @Override
        @Transactional
        public void save(User user) {
            DefaultTransactionDefinition def = new DefaultTransactionDefinition();
            // explicitly setting the transaction name is something that can only be done programmatically
            def.setName("SomeTxName");
            def.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRED);

            TransactionStatus status = transactionManager.getTransaction(def);
            try {
                // execute your business logic here
                //db operation
            } catch (Exception ex) {
                transactionManager.rollback(status);
                throw ex;
            }
        }
    }
</pre>